### PR TITLE
added theme support

### PR DESCRIPTION
**Pull request by Gnarmagon**
added theme pkg support
I only compiled it in "Bash on Ubuntu on Windows"  (doesn't work on windows atm)...

It's the first time I wrote some C code.

### CODE REVIEW

**Comment by Gnarmagon** [comment]
Compiles now under Windows and I fixed some warnings....(caused by my own stuff XD)

**Comment by Gnarmagon** [comment]
binaries for Linux and Windows:
[pkg2zip-binaries.zip](https://github.com/mmozeiko/pkg2zip/files/1825537/pkg2zip-binaries.zip)

**Comment by TheRadziu** [comment]
tested with 5 themes, works as intended. Too bad vitasmith didnt add theme support to Refresh LiveArea like he did with DLCs so we could use raw files instead of bgdl.

But heck, as long as it works.

**Comment by mmozeiko** [comment]
I do not think I want pdb approach in pkg2zip. That's why it did not have it for DLCs. I'm sure there should by way to install themes with same approach as main game files or dlcs.

Also your pull request needs multiple changes:

1) remove `pause` from build.cmd. This makes CI testing on Appveyor impossible. And having pause there is super annoying - that's extra enter you need to press every time you build locally.

2) fix your indenting, currently it's all over place. And fix tabs vs spaces. And use `type* variable` not `type *variable`. Use same style as rest of code.

3) don't use system dependent functions in generic code (stat). Those should go into sys.c file.

4) no fopen/fwrite/fclose. sys.c is for all system dependent code that

5) no malloc please. All of the code (except zip files) uses no dynamic memory allocations.

6) too many hardcoded sizes for second argument to snprintf. Use sizeof.

7) useless includes - errno.h, 

8) no global variables - `next_dir`

**Comment by TheRadziu** [comment]
as I said, DLC-like approach requires someone to add theme support to vitashell's refresh.c first, because of VitaSmith we could move DLCs from bgdl method to regular file extraction. Without it - only bgdl can do.

**Comment by mmozeiko** [comment]
I perfectly fine remember how DLC bgdl method was changed to normal install. I do see how that is relevant to this. DLC != theme.

**Comment by TheRadziu** [comment]
> I do not think I want pdb approach in pkg2zip. That's why it did not have it for DLCs. I'm sure there should by way to install themes with same approach as main game files or dlcs.

Unless I misunderstood that part. My general opinion is: if we have working tool for theme extraction via bgdl, someone will do commit refresh.c change that'd allow 'same approach as main game or dlc', not the other way around

**Comment by Gnarmagon** [comment]
thanks for the feedback, will put in some more work and fix those issues....

**Comment by MaouSan1992** [comment]
i don´t understand how to install the themes from Nopaystation in the Psvita , in the official page says that must copy the bgdl in the vita but when i do that nophing happens and if i reboot the vita all dessapear ? 

it is any tutorial for that ? with images if i could , i downloaded a lot of themes but i dont know how to install in the Vita ...

**Comment by Luro02** [comment]
this is the wrong place to ask those questions...
please go on their discord or ask on gbatemp for help.

**Pull request closed without merging**
